### PR TITLE
fix: handle libkrun machines

### LINKED ISSUE #722: Fails root validation check when using macOS + libkrun
### Bug description

Cannot build because it will show the "needs to be root" error.

This is because when using libkrun on macOS, `podman machine ls` will be blank.

We need to:

If we fail validation check and we are on macOS we should:
1. Use `podman system connection ls`
2. Find the default
3. Check the name has `-root`
4. If name does not have root, also check URI that the socket is `/run/podman`
5. Say that it's root podman machine if it passes either.

Luckily it is a validation check and if it it give a false positive, it will fail anyways in `bootc-image-builder` when building, as they ALSO have a validation check to make sure it's root.

### Operating system

mac m1

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

cc @cbr7

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #722

### What does this PR do?

Properly handle libkrun machines

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#722

### How to test this PR?

1. Create a libkrun machine
2. Initiate a bootc build

### CODE REVIEW

**Review by cdrage — APPROVED** [review]
https://github.com/user-attachments/assets/cc22e956-7eda-46a1-9d41-d2fb0d4b7254

LGTM!

Thank you for the tests as well, it's unfortunate we do not have a direct Podman Desktop API to handle this, but this solution works.

File: packages/backend/src/machine-utils.ts [hunk 1]
```diff
@@ -21,15 +21,50 @@ import * as os from 'node:os';
 import * as path from 'node:path';
 import * as fs from 'node:fs';
 import { satisfies, coerce } from 'semver';
+import type { ContainerProviderConnection } from '@podman-desktop/api';
+
+function getMachineProviderEnv(connection: extensionApi.ContainerProviderConnection): string {
+  switch (connection.vmType) {
```
Comment (cdrage) [inline packages/backend/src/machine-utils.ts:27]: maybe we should lowercase vmType before checking so we don't have to add `Wsl` as well?

but just a nitpick, otherwise LGTM.

Comment (jeffmaury) [reply packages/backend/src/machine-utils.ts:27]: I let it on purpose because the 2 values (wsl and Wsl) are there because of a bug in Podman Desktop core that replace the lowercase vmType by the uppercase one in order to get a better displayed value but that's incorrect and in a future only wsl (as well as libkrun) will be sent in 1.13

Comment (cdrage) [reply packages/backend/src/machine-utils.ts:27]: no problem! lgtm
